### ISSUE TITLE
Release library

### ISSUE THREAD

**Issue by moteus** [daurnimator/lua-idn2#1]
Can you please release this library and put it to the LuaRocks?

**Comment by daurnimator** [comment]
Hrm. I wonder why I didn't.
I ran the code and audited it for any mistakes; seems fine.
Will make a 0.1 release now.

**Comment by daurnimator** [comment]
Done. 
  - https://github.com/daurnimator/lua-idn2/releases/tag/v0.1
  - https://luarocks.org/modules/daurnimator/idn2/0.1-0
